services:
  vidro.api:
    image: ${DOCKER_REGISTRY-}vidroapi
    build:
      context: .
      dockerfile: vidro.api/Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__VidroConnection=Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      - vidro-network

  postgres:
    image: postgres:15
    container_name: vidro_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./vidro.database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vidro-network

volumes:
  postgres_data:

networks:
  vidro-network:
    driver: bridge
